apiVersion: v1
kind: Service
metadata:
  name: crunchy-alertmanager
  labels:
    name: crunchy-alertmanager
    vendor: crunchydata
  {{- include "crunchy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.alertmanager.type }}
  selector:
    name: crunchy-alertmanager
  {{- include "crunchy.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.alertmanager.ports | toYaml | nindent 2 -}}
