apiVersion: apps/v1
kind: Deployment
metadata:
  name: crunchy-alertmanager
  labels:
  {{- include "crunchy.labels" . | nindent 4 }}
  annotations:
    deployment.kubernetes.io/revision: "1"
spec:
  replicas: {{ .Values.alertmanager.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: postgres-operator-monitoring
      name: crunchy-alertmanager
    {{- include "crunchy.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: postgres-operator-monitoring
        name: crunchy-alertmanager
      {{- include "crunchy.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - args: {{- toYaml .Values.alertmanager.alertmanager.args | nindent 8 }}
        env:
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.alertmanager.alertmanager.image.repository }}:{{ .Values.alertmanager.alertmanager.image.tag
          | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.alertmanager.alertmanager.imagePullPolicy }}
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /-/healthy
            port: 9093
            scheme: HTTP
          initialDelaySeconds: 25
          periodSeconds: 20
          successThreshold: 1
          timeoutSeconds: 1
        name: alertmanager
        ports:
        - containerPort: 9093
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /-/ready
            port: 9093
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/alertmanager
          name: alertmanagerconf
        - mountPath: /alertmanager
          name: alertmanagerdata
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 26
        supplementalGroups:
        - 65534
      serviceAccount: alertmanager
      serviceAccountName: crunchy-alertmanager
      terminationGracePeriodSeconds: 30
      volumes:
      - name: alertmanagerdata
        persistentVolumeClaim:
          claimName: crunchy-alertmanagerdata
      - configMap:
          defaultMode: 420
          name: crunchy-alertmanager-config
        name: alertmanagerconf
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crunchy-grafana
  labels:
  {{- include "crunchy.labels" . | nindent 4 }}
  annotations:
    deployment.kubernetes.io/revision: "1"
spec:
  replicas: {{ .Values.grafana.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: postgres-operator-monitoring
      name: crunchy-grafana
    {{- include "crunchy.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: postgres-operator-monitoring
        name: crunchy-grafana
      {{- include "crunchy.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: GF_PATHS_DATA
          value: {{ quote .Values.grafana.grafana.env.gfPathsData }}
        - name: GF_SECURITY_ADMIN_USER__FILE
          value: {{ quote .Values.grafana.grafana.env.gfSecurityAdminUserFile }}
        - name: GF_SECURITY_ADMIN_PASSWORD__FILE
          value: {{ quote .Values.grafana.grafana.env.gfSecurityAdminPasswordFile }}
        - name: PROM_HOST
          value: {{ quote .Values.grafana.grafana.env.promHost }}
        - name: PROM_PORT
          value: {{ quote .Values.grafana.grafana.env.promPort }}
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.grafana.grafana.image.repository }}:{{ .Values.grafana.grafana.image.tag
          | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.grafana.grafana.imagePullPolicy }}
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /api/health
            port: 3000
            scheme: HTTP
          initialDelaySeconds: 25
          periodSeconds: 20
          successThreshold: 1
          timeoutSeconds: 1
        name: grafana
        ports:
        - containerPort: 3000
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /api/health
            port: 3000
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data
          name: grafanadata
        - mountPath: /conf/admin
          name: grafana-secret
        - mountPath: /etc/grafana/provisioning/datasources
          name: grafana-datasources
        - mountPath: /etc/grafana/provisioning/dashboards
          name: grafana-dashboards
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 26
        supplementalGroups:
        - 65534
      serviceAccount: grafana
      serviceAccountName: crunchy-grafana
      terminationGracePeriodSeconds: 30
      volumes:
      - name: grafanadata
        persistentVolumeClaim:
          claimName: crunchy-grafanadata
      - name: grafana-secret
        secret:
          defaultMode: 420
          secretName: crunchy-grafana-secret
      - configMap:
          defaultMode: 420
          name: crunchy-grafana-datasources
        name: grafana-datasources
      - configMap:
          defaultMode: 420
          name: crunchy-grafana-dashboards
        name: grafana-dashboards
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crunchy-prometheus
  labels:
  {{- include "crunchy.labels" . | nindent 4 }}
  annotations:
    deployment.kubernetes.io/revision: "1"
spec:
  replicas: {{ .Values.prometheus.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: postgres-operator-monitoring
      name: crunchy-prometheus
    {{- include "crunchy.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: postgres-operator-monitoring
        name: crunchy-prometheus
      {{- include "crunchy.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.prometheus.prometheus.image.repository }}:{{ .Values.prometheus.prometheus.image.tag
          | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.prometheus.prometheus.imagePullPolicy }}
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /-/healthy
            port: 9090
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 20
          successThreshold: 1
          timeoutSeconds: 1
        name: prometheus
        ports:
        - containerPort: 9090
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /-/ready
            port: 9090
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/prometheus
          name: prometheusconf
        - mountPath: /prometheus
          name: prometheusdata
        - mountPath: /etc/prometheus/alert-rules.d
          name: alertmanagerrules
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 26
        supplementalGroups:
        - 65534
      serviceAccount: prometheus-sa
      serviceAccountName: crunchy-prometheus-sa
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: crunchy-prometheus
        name: prometheusconf
      - name: prometheusdata
        persistentVolumeClaim:
          claimName: crunchy-prometheusdata
      - configMap:
          defaultMode: 420
          name: crunchy-alertmanager-rules-config
        name: alertmanagerrules