apiVersion: v1
kind: Service
metadata:
  name: crunchy-grafana
  labels:
    name: crunchy-grafana
    vendor: crunchydata
  {{- include "crunchy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.grafana.type }}
  selector:
    name: crunchy-grafana
  {{- include "crunchy.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.grafana.ports | toYaml | nindent 2 -}}