apiVersion: v1
kind: Secret
metadata:
  name: crunchy-grafana-secret
  labels:
    vendor: crunchydata
  {{- include "crunchy.labels" . | nindent 4 }}
data:
  password: {{ default "admin" .Values.grafanaSecret.password | b64enc | quote }}
  username: {{ default "admin" .Values.grafanaSecret.username | b64enc | quote }}
type: Opaque
