apiVersion: v1
kind: ConfigMap
metadata:
  name: crunchy-prometheus
  labels:
    vendor: crunchydata
  {{- include "crunchy.labels" . | nindent 4 }}
data:
  prometheus.yml: {{ .Values.prometheus.prometheusYml | toYaml | indent 1 }}
---
apiVersion: v1
kind: Service
metadata:
  name: crunchy-prometheus
  labels:
    name: crunchy-prometheus
    vendor: crunchydata
  {{- include "crunchy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.prometheus.type }}
  selector:
    name: crunchy-prometheus
  {{- include "crunchy.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.prometheus.ports | toYaml | nindent 2 -}}