apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: crunchy-prometheusdata
  labels:
    vendor: crunchydata
  {{- include "crunchy.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.prometheusdata.storageRequest | quote }}