apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: crunchy-prometheus-cr
  labels:
    vendor: crunchydata
  {{- include "crunchy.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch