apiVersion: v1
kind: ServiceAccount
metadata:
  name: crunchy-alertmanager
  labels:
    vendor: crunchydata
  {{- include "crunchy.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.alertmanager.serviceAccount.annotations | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: crunchy-grafana
  labels:
    vendor: crunchydata
  {{- include "crunchy.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.grafana.serviceAccount.annotations | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: crunchy-prometheus-sa
  labels:
    vendor: crunchydata
  {{- include "crunchy.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.prometheusSa.serviceAccount.annotations | nindent 4 }}